# Generated by Django 3.1.5 on 2021-09-28 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='seeds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('subname', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=128)),
                ('germination', models.IntegerField()),
                ('date_on_packet', models.DateField()),
                ('depth', models.IntegerField()),
                ('light', models.CharField(choices=[('1', 'shade'), ('2', 'partial sun'), ('3', 'full sun')], max_length=1)),
                ('spacing', models.IntegerField()),
                ('harvest', models.IntegerField()),
            ],
        ),
    ]
