# Generated by Django 3.1.5 on 2021-09-29 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seeds',
            name='depth',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='seeds',
            name='spacing',
            field=models.CharField(max_length=10),
        ),
    ]
