# Generated by Django 3.1.5 on 2021-09-29 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeds', '0003_auto_20210929_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seeds',
            name='date_on_packet',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='seeds',
            name='germination',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='seeds',
            name='light',
            field=models.CharField(blank=True, choices=[('1', 'shade'), ('2', 'partial sun'), ('3', 'full sun')], max_length=1),
        ),
        migrations.AlterField(
            model_name='seeds',
            name='sow',
            field=models.DateField(default='2022-05-04'),
        ),
        migrations.AlterField(
            model_name='seeds',
            name='subname',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
