# Generated by Django 3.1.5 on 2021-09-29 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeds', '0004_auto_20210929_0115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantingbeds',
            name='section',
        ),
        migrations.AddField(
            model_name='plantingbeds',
            name='zone',
            field=models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five')], default=1),
        ),
    ]
