# Generated by Django 3.2 on 2021-09-29 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeds', '0005_auto_20210929_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planted',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='plantingbeds',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='seeds',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
