# Generated by Django 3.2 on 2021-09-29 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeds', '0006_auto_20210929_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantingbeds',
            name='zone',
            field=models.IntegerField(choices=[('Greenhouse', 'Green House'), (1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five')], default=1),
        ),
    ]
