# Generated by Django 3.2 on 2021-09-29 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeds', '0014_alter_plantingbeds_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='planted',
            name='date_germination',
            field=models.DateField(blank=True, default='2022-05-04'),
        ),
        migrations.AddField(
            model_name='planted',
            name='date_harvest',
            field=models.DateField(blank=True, default='2022-05-04'),
        ),
        migrations.AlterField(
            model_name='plantingbeds',
            name='zone',
            field=models.CharField(choices=[('GH', 'Green house'), ('Z1', 'Zone One'), ('Z2', 'Zone Two'), ('Z3', 'Zone Three'), ('Z4', 'Zone Four'), ('Z5', 'Zone Five'), ('ID', 'Indoors')], default=1, max_length=64),
        ),
    ]
