# Generated by Django 3.2.7 on 2021-10-01 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seeds', '0015_auto_20210929_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planted',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planteds', to='seeds.plantingbeds'),
        ),
        migrations.AlterField(
            model_name='planted',
            name='seed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planteds', to='seeds.seeds'),
        ),
    ]
