# Generated by Django 3.2.7 on 2021-10-01 20:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeds', '0016_auto_20211001_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planted',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(2021, 10, 1)),
        ),
    ]
