# Generated by Django 3.2.7 on 2021-10-01 20:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('seeds', '0017_alter_planted_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planted',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
