# Generated by Django 3.2.7 on 2021-10-01 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeds', '0019_alter_seeds_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seeds',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
